### ISSUE TITLE
Useless website

### ISSUE THREAD

**Issue by jorgesumle** [ChiweenieDijon/noonian#1]
`wee` is the only source code of the website. It should be a little more informative. Also, I had to add a security exception to access.
![captura de pantalla de 2016-08-18 15 26 33](https://cloud.githubusercontent.com/assets/14212780/17775372/3ed79d9c-6558-11e6-82f1-f9269e1f9d31.png)

**Comment by ChiweenieDijon** [comment]
LOL, Agreed!  Has been resolved.
