### ISSUE TITLE
Containerize

### ISSUE THREAD

**Issue by violkimuw** [ChiweenieDijon/noonian#47]
Let's dockerize this project!

**Comment by violkimuw** [comment]
PR - https://github.com/ChiweenieDijon/noonian/pull/48

**Comment by nicechester** [comment]
We must use compose - https://docs.docker.com/compose/gettingstarted/#step-3-define-services-in-a-compose-file
mongo can be separated out of noonian docker image - https://hub.docker.com/_/mongo/
